safe:      true
permalink: date
markdown:  redcarpet
highlighter: rouge
exclude:   [ README.md, Gemfile, .*, bower.json ]

# Setup
title: "AccelerateIDB"
tagline: ""
url: https://a40b.github.io
baseurl: "https://a40b.github.io"
