safe:      true
permalink: date
markdown:  redcarpet
highlighter: pygments
exclude:   [ README.md, Gemfile, vendor, .*, bower.json ]

# Setup
title: "AccelerateIDB"
tagline: ""
url: http://accelerateidb.com
baseurl: "http://accelerateidb.com"
